# vim: ai et ts=2 st=2 sw=2 :
---
- name: Disable DNS for network manager
  become: yes
  community.general.ini_file:
    path: /etc/NetworkManager/conf.d/90-dns-none.conf
    section: main
    option: dns
    value: 'none'
    mode: '0644'
    no_extra_spaces: true
  register: conf_nm_dns

- name: Check if network manager runs
  ansible.builtin.shell: pgrep NetworkManager
  failed_when: false
  changed_when: false
  register: network_manager_running
  check_mode: false

- name: Distribute resolv.conf template
  become: yes
  ansible.builtin.template:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: '0644'

- name: Reload network manager
  become: yes
  ansible.builtin.service:
    name: NetworkManager
    state: reloaded
  when:
    - conf_nm_dns is changed
    - network_manager_running.rc == 0
